### PR TITLE
Fix npm repo name

### PR DESCRIPTION
**Pull request by machawk1**

### CODE REVIEW

**Comment by retrohacker** [comment]
Hey @machawk1,

Interested in how you found this project and what you are using it for!

It is currently unmaintained and I suspect it is in a rather broken state.

**Comment by retrohacker** [comment]
If you like it, it could use a new home :smile:

**Comment by machawk1** [comment]
@retrohacker Found out about this project by tracing it through you from your peerweb project, via webtorrent, via ipfs, via one of my own projects ( https://github.com/oduwsdl/ipwb ). I'm not sure I would do it justice in giving it a new home but will fork and/or submit bugs when I come across them.

**Comment by retrohacker** [comment]
Oh nice! Great to meet you :smile:

**Pull request merged**
